package Objects;

import org.openqa.selenium.By;

public class Locators {

    public static By user_name = By.xpath("//input[@placeholder='Username']");
    public static By password = By.xpath("//input[@placeholder='Password']");
    public static By login_button = By.xpath("//button[text()='Login']");
    public static By home_button = By.xpath("//div[text()='Home']");
    public static By profile = By.xpath(" //div[@class='d-flex']");
    public static By log_out = By.xpath("//span[text()='Logout']");
    public static By page_title = By.xpath("//div[text()='Jewel Applications']");
    public static By autolytics = By.xpath("(//div[text()='Autolytics'])[2]");
    public static By bridge_token = By.xpath("(//div[text()='Bridge Token'])[2]");
    public static By copy_bridge_token = By.xpath("//div[@class='copyIcon col-2 d-flex justify-content-center align-items-center']");
    public static By copy_alert = By.xpath("//div[text()='Copied !']");
    public static By change_token = By.xpath("//div[text()='Change Token']");
    public static By date_tab = By.xpath("//div[@class='createdOn mt-3']");
    public static By change_token_alert = By.xpath("//div[text()='Bridge Token Changed Successfully.']");
    public static By pelement = By.xpath("//div[@class='d-flex']");
    public static By lelement = By.xpath("//div[@class='dropdown-item mx-auto text-center']");
    public static By cards = By.xpath("//div[@class='card-body ms-2']");
    public static By card_one = By.xpath("(//div[@class='mt-3 cardName'])[1]");
    public static By content_card_one = By.xpath("(//div[@class='mt-1 appCardContent'])[1]");
    public static By card_two = By.xpath("(//div[@class='mt-3 cardName'])[2]");
    public static By content_card_two = By.xpath("(//div[@class='mt-1 appCardContent'])[2]");
    public static By login_alert = By.xpath("//div[@role='alert']");
    public static By three_lines_button = By.xpath("//img[@class='collapseBtn ms-3 mt-3 mb-2']");
    public static By signup_button = By.xpath("//span[text()='Sign up']");
    public static By first_name = By.xpath("//input[@placeholder='Firstname']");
    public static By last_name = By.xpath(" //input[@placeholder='Lastname']");
    public static By email = By.xpath("//input[@placeholder='Email']");
    public static By confirm_pass = By.xpath("//input[@placeholder='Confirm Password']");
    public static By company_name = By.xpath("//input[@placeholder='Company Name']");
    public static By register_button = By.xpath("//button[text()='Register']");
    public static By register_alert = By.xpath("//div[text()='User Registered.']");
    public static By create_report = By.xpath("//span[text()='Create Report']");
    public static By report_name_button = By.xpath("//span[text()='Select Report Name']");
    public static By suite_run = By.xpath("//li[text()='Suite Run Report']");
    public static By project_name = By.xpath("//div[text()='Select Project Name(s)']");
    public static By project_name_selection = By.xpath("//span[text()='JEWEL-UI-JV']");
    public static By cross_button = By.xpath("//button[@class='p-multiselect-close p-link']");
    public static By env_tab = By.xpath("//div[text()='Select Environment(s)']");
    public static By select_env = By.xpath("//span[text()='Dev']");
    public static By cbutton = By.xpath("//span[@class='p-multiselect-close-icon pi pi-times']");
    public static By date_range_tab = By.xpath("//span[text()='Select Date Range']");
    public static By select_date = By.xpath("//li[text()='Last 24 hours']");
    public static By generate_button = By.xpath("//button[text()='GENERATE']");
    public static By new_tab = By.xpath("//i[@class='pi pi-plus-circle']");
    public static By left_tabs = By.xpath("//div[@class='tabPane  align-items-center nav nav-pills']/div[starts-with(@id,'left-tabs')]");
    public static By left_most_tab = By.xpath("//button[@id='slideLeftLeft']");
    public static By right_most_tab = By.xpath("//button[@id='slideRightRight']");
    public static By slide_left = By.xpath("//button[@id='slideLeft']");
    public static By slide_right = By.xpath("//button[@id='slideRight']");
    public static By copy_report_link = By.xpath("//label[@title='Copy Report Link']");
    public static By check_text_of_report = By.xpath("//div[@class='me-3 content d-flex align-items-center']");
    public static By tabs = By.xpath("(//div[starts-with(@id,'left-tabs-example-tabParent')])[4]/a");
    public static By parent_tab = By.xpath("(//div[starts-with(@id,'left-tabs-example-tabParent')])[3]/a");
    public static By tab_select = By.xpath("(//div[starts-with(@id,'left-tabs-example-tabParent')])[1]/a");
    public static By right_most = By.xpath("(//div[starts-with(@id,'left-tabs-example-tabParent')])[5]/a");

    public static By left_next = By.xpath("(//div[starts-with(@id,'left-tabs-example-tabParent')])[4]/a");


    public static By logIn = By.xpath("//*[@class='btn-text-login fw-normal']");
    public static By searchBox = By.xpath("//*[@title='Search']");
    public static By jewel = By.xpath("//*[@class='LC20lb MBeuO DKV0Md']");
    public static By username = By.xpath("//*[@class='form-control']");
    public static By passwordm = By.xpath("//*[@type='password']");
    public static By register_newww = By.xpath("//span[text()=\"Register New User\"]");
    public static By close = By.xpath("//*[@class='crossicon']");
    public static By LoginButton = By.xpath("//*[@type='submit']");
    public static By pricing = By.xpath("//*[@href='#/pricing']");
    public static By pricingheading = By.xpath("//*[@class='headingtext']");
    public static By eye = By.xpath("//*[@class=\"pi pi-eye\"]");
    public static By eyeclose = By.xpath("//*[@class=\"pi pi-eye-slash\"]");
    public static By pricingsubheading = By.xpath("//*[@class='headingsubtext']");
    public static By jewelheading = By.xpath("//*[@class='mainHead mt-5 ms-5']");
    public static By jewelsubheading = By.xpath("//*[@class='subHead ms-5']");
    // public static By jewelink = By.xpath("//*[@src='/static/media/logo.67ff04482762962f73e1e6ad28de5771.svg']");
    public static By whatisjewel = By.xpath("//*[@class='headtext']");
    public static By aboutus = By.xpath("//*[@class='under']");
    public static By content = By.xpath("//*[@class='underText text-center px-5 my-5 ']");
    public static By viewreport = By.xpath("//*[text()='View Report']");
    public static By viewreportcontent = By.xpath("//*[@class='whatisData mb-5 px-3']");
    public static By pricingcontent = By.xpath("//*[@class='paraText']");
    public static By jewelconetnt = By.xpath("//*[@class='subHead ms-5']");
    public static By runtest = By.xpath("//*[text()='Run Test Suite']");
    public static By runtestc = By.xpath("(//*[@class='whatisData mb-5 px-3'])[2]");
    public static By facebook = By.xpath("(//*[@class='icon_links'])[1]");
    public static By twitter = By.xpath("(//*[@class='icon_links'])[2]");
    public static By instagram = By.xpath("(//*[@class='icon_links'])[3]");
    public static By linkedin = By.xpath("(//*[@class='icon_links'])[4]");
    public static By jeweldashboard = By.xpath("//*[text()='Jewel dashboard']");
    public static By gempyp = By.xpath("//*[text()=' GemPYP']");
    public static By gemprf = By.xpath("//*[text()='GemPRF']");
    public static By gemjar = By.xpath("//*[text()='GemJAR']");
    public static By pricingbutton = By.xpath("//*[text()='Pricing ']");
    public static By autolyticsm = By.xpath("//*[text()='Autolytics']");
    public static By createReport = By.xpath("//*[@class='emptyText py-2 px-3 btn btn-sm ']");
    public static By checkboxxx = By.xpath("(//div[@class=\"p-checkbox-box\"])[1]");
    public static By reporting_new_btn = By.xpath("//div[text()=\"Reporting\"]");
    public static By reportNameScroll = By.xpath("//*[span='Select Report Name']");
    public static By suiteRunReport = By.xpath("//*[text()='Suite Run Report']");
    public static By projectScroll = By.xpath("//*[@class='p-multiselect-label p-placeholder']");
    public static By gemEcoApis = By.xpath("//*[span='GEMECOSYSTEM_APIS']");
    public static By enviromentScroll = By.xpath("//*[text()='Select Environment(s)']");
    public static By prod = By.xpath("//*[span='Prod']");
    public static By dateRangeScroll = By.xpath("//*[span='Select Date Range']");
    public static By thisYear = By.xpath("//*[@aria-label='This Year']");
    public static By seven_days = By.xpath("//li[text()=\"Last 7 days\"]");
    public static By generate = By.xpath("//*[@class='btn btn-sm stn-success themeBtn']");
    public static By copyButton = By.xpath("//*[@class='svg-inline--fa fa-copy mx-2 tabIcon']");
    public static By newTab = By.xpath("//*[@class='svg-inline--fa fa-square-arrow-up-right mx-2 tabIcon']");
    public static By createReportButton = By.xpath("//*[@class=' ms-3 btn-success btn themeBtn']");
    public static By signup = By.xpath("//*[@class='btn-text-signup fw-bold']");
    public static By firstname = By.xpath("//*[@placeholder='Firstname']");
    public static By lastname = By.xpath("//*[@placeholder='Lastname']");
    public static By username1 = By.xpath("//*[@placeholder='Username']");
    public static By emailm = By.xpath("//*[@placeholder='Email']");
    public static By password1 = By.xpath("//*[@placeholder='Password']");
    public static By confirmpass = By.xpath("//*[@placeholder='Confirm Password']");
    public static By companyname = By.xpath("//*[@placeholder='Company Name']");
    public static By register = By.xpath("//*[@class='mt-3 btn btn-primary text-center px-5']");
    public static By span = By.xpath("(//*[span=18])[1]");
    public static By sno = By.xpath("//*[text()='S No']");
    public static By secondPage = By.xpath("//*[@class='p-button p-component p-paginator-page p-paginator-element p-link p-highlight']");
    public static By total = By.xpath("//*[text()='Total 18 Records Found']");
    public static By crossCreateReport = By.xpath("//*[@class='p-dialog-header-icon p-dialog-header-close p-link']");
    public static By pass = By.xpath("//div[@class='btn btn-sm statusBtn btn-success pass-btn ']");
    public static By filter = By.xpath("(//button[@class='p-column-filter-menu-button p-link'])[4]//span");
    public static By selectFilter = By.xpath("//*[text()='Select Option(s)']");
    public static By selectFilter100 = By.xpath("//*[text()='1 items selected']");
    public static By selectPass = By.xpath("//div[text()='PASS']//ancestor::span//preceding-sibling::div/div");
    public static By closeFilter = By.xpath("//*[@class='p-multiselect-close p-link']//span");
    public static By selct_pass_text = By.xpath("//span[@class=\"image-text\"]//div[text()='PASS']");
    public static By selectFilter1 = By.xpath("//*[text()='1 items selected']");
    public static By exe = By.xpath("//div[text()='INFO']//ancestor::span//preceding-sibling::div/div");
    public static By select_exe_text = By.xpath("//span[@class='image-text']/div[text()='EXE']");
    public static By exe1 = By.xpath("//div[@class='btn btn-sm statusBtn btn-success exe-btn']");
    public static By fail = By.xpath("//div[text()='FAIL']//ancestor::span//preceding-sibling::div/div");
    public static By select_fail_text = By.xpath("//span[@class=\"image-text\"]//div[text()='FAIL']");
    public static By fail1 = By.xpath("//div[@class='btn btn-sm statusBtn btn-success fail-btn ']");
    public static By warn = By.xpath("//div[text()='PASS']//ancestor::span//preceding-sibling::div/div");
    public static By select_warn_text = By.xpath("//span[@class='image-text']/div[text()='WARN']");
    public static By warn1 = By.xpath("//div[@class='btn btn-sm statusBtn btn-success warn-btn']");
    public static By filter1 = By.xpath("(//button[@class='p-column-filter-menu-button p-link'])[7]//span");
    public static By selectDate = By.xpath("(//div[@class='p-multiselect-representative-option'])[3]//span");
    public static By select_date_text = By.xpath("(//div[@class='text-center'])[4]");
    public static By action = By.xpath("(//div[@class='actionBtn'])[1]");
    public static By executionR = By.xpath("//*[text()='Execution Report']");
    public static By newtb_button = By.xpath("(//*[@class='svg-inline--fa fa-square-arrow-up-right mx-2 tabIcon'])[2]");
    public static By testcaseDetail = By.xpath("//*[text()='Testcase Details']");
    public static By selectFilter3 = By.xpath("(//*[@class='p-column-filter-menu-button p-link'])[11]");
    public static By select_filter = By.xpath("(//*[@class='p-multiselect-trigger'])");
    public static By click_filter = By.xpath("(//*[@class='p-checkbox-box'])[2]");
    public static By close_filter = By.xpath("(//*[@class='p-multiselect-close-icon pi pi-times'])");
    public static By close_filter1 = By.xpath("(//*[@class='btn btn-sm statusBtn btn-success pass-btn'])[9]");
    public static By inside_filter_text = By.xpath("(//*[text()='August 16, 2022 5:20:03 PM (IST)'])[3]");
    public static By outside_filter_text = By.xpath("(//*[text()='August 16, 2022 5:20:03 PM (IST)'])[1]");
    public static By login_screen = By.xpath("//span[text()='Log in']");
    public static By scroll_down = By.xpath("(//*[@class=\"p-dropdown-trigger\"])[2]");
    public static By select_24 = By.xpath("(//*[@class=\"p-dropdown-item\"])[1]");
    public static By suite_detail = By.xpath("(//*[text()=\"suite details are not found\"])");
    public static By all_f = By.xpath("(//*[text()=\"All fields are required !\"])");
    public static By cross_b = By.xpath("//*[@class=\"cross btn-sm ms-auto d-flex align-items-center\"]");
    public static By open_n = By.xpath("//*[text()=\"Open New Tab\"]");
    public static By suite_sum = By.xpath("//*[text()=\"Suite Summary Report\"]");
    public static By suite_sum_text = By.xpath("//*[text()=\"Suite Summary Report\"]");
    public static By select_all = By.xpath("(//*[@class=\"p-checkbox-box\"])[1]");
    public static By select_all2 = By.xpath("(//*[@class=\"p-checkbox-box\"])[1]");
    public static By pie_filter = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[4]");
    public static By select_pie = By.xpath("(//*[@class=\"p-multiselect-trigger\"])");
    public static By select_pie2 = By.xpath("(//*[@class=\"p-checkbox-box\"])[2]");
    public static By pie1 = By.xpath("(//*[@class=\"text-center mb-3 overHead\"])[1]");
    public static By pie2 = By.xpath("(//*[@class=\"text-center mb-3 overHead\"])[2]");
    public static By close_pie = By.xpath("(//*[@class=\"p-multiselect-close p-link\"])");
    public static By close_pie2 = By.xpath("(//*[@class=\"image-text\"])[1]");
    public static By no_select = By.xpath("(//*[@class=\"p-checkbox-icon p-c pi pi-check\"])");
    public static By pie_countt = By.xpath("//canvas");
    public static By total_text = By.xpath("(//*[@class=\"p-paginator-current\"])");
    public static By edit_report_btn = By.xpath("//*[text()=\"Edit Report\"]");
    public static By suite_rpt_clck = By.xpath("//*[span='Suite Summary Report']");
    public static By sun_rn_rpt_txt = By.xpath("//*[text()=\"Suite Run Report\"]");
    public static By envrmnt_fltrr = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[3]");
    public static By betaa = By.xpath("(//*[@class=\"p-checkbox-box\"])[2]");
    public static By beta_txt = By.xpath("(//*[text()=\"beta\"])[3]");
    public static By betas = By.xpath("(//*[text()=\"beta\"])");
    public static By betaa2 = By.xpath("(//*[@class=\"p-checkbox-icon p-c pi pi-check\"])");
    public static By shared_reportt = By.xpath("//*[text()=\"Shared Report\"]");
    public static By shared_pie = By.xpath("//*[@class=\"p-column-filter-menu-button p-link p-column-filter-menu-button-active\"]");
    public static By suite_diag = By.xpath("//*[text()=\"Suite Diagnose Report\"]");
    public static By testcase_diag = By.xpath("//*[text()=\"Testcase Diagnose Report\"]");
    public static By testcase_run_rpt = By.xpath("//*[text()=\"Testcase Run Report \"]");
    public static By testcase_summ_rpt = By.xpath("//*[text()=\"Testcase Summary Report\"]");
    public static By last_run_status = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[4]");
    public static By suite_run_filter = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[4]");
    public static By select_daily_beta_reg = By.xpath("(//*[@class=\"p-checkbox-box\"])[2]");
    public static By daily_beta_reg_text = By.xpath("(//span[text()=\"FEATURE_REGRESSION\"])[2]");
    public static By daily_betas_reg_text = By.xpath("(//span[text()=\"FEATURE_REGRESSION\"])");
    public static By project_name_fltr = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[1]");
    public static By pygem_project_select = By.xpath("(//*[@class=\"p-checkbox-box\"])[4]");
    public static By pygem_project_txt = By.xpath("//span[text()=\"gemecosystem_apis\"]");
    public static By pygem_project_txts = By.xpath("(//*[text()=\"pygem_project\"])");
    public static By broken_index_filtr = By.xpath("(//*[@class=\"p-column-filter-menu-button p-link\"])[4]");
    public static By broken_index_slct = By.xpath("(//*[@class=\"p-checkbox-box\"])[2]");
    public static By broken_index_txt = By.xpath("(//span[text()=\"0\"])[7]");
    public static By broken_index_txts = By.xpath("(//span[text()=\"0\"])");
    public static By test_case_run_rpt_txt = By.xpath("(//*[@class=\"p-datatable-header\"])");
    public static By testTool = By.xpath("//div[text()=\"Test Tool\"]");
    public static By suite = By.xpath("//div[text()=\"Suite\"]");
    public static By testCasePlus = By.xpath("(//*[local-name()='svg' and @data-icon='square-plus']/*[local-name()='path'])[1]");
    public static By testCasePlus2 = By.xpath("(//*[local-name()='svg' and @data-icon='square-plus']/*[local-name()='path'])[2]");
    public static By testCasePlus3 = By.xpath("(//*[local-name()='svg' and @data-icon='square-plus']/*[local-name()='path'])[3]");
    public static By testcase = By.xpath("//div[text()=\"Testcases\"]");
    public static By getTestcaseCount = By.xpath("(//div[@class=\"text-left\"]//span)[7]");
    public static By getTestcaseCountAlter = By.xpath("(//div[@class=\"text-left\"]//span)[7]");
    public static By create_testcase_button = By.xpath("//div[text()=\"Create Testcase\"]");
    public static By importFromLib = By.xpath("//div[text()=\"Import from Library\"]");
    public static By create_suite_button = By.xpath("//div[text()=\"Create Suite\"]");
    public static By upload_button = By.xpath("//div[text()=\"Upload\"]");
    public static By globalCross = By.xpath("//span[@class=\"p-dialog-header-close-icon pi pi-times\"]");

    public static By fileUpload = By.xpath("//input[@class=\"mx-1\"]");
    public static By browseBtn = By.xpath("//div[text()=\"Browse\"]");
    public static By tescaseSize = By.xpath("//td[@class=\"columnsPrime\"]");
    public static By suite_ID = By.xpath("(//div[@class=\"text-left\"]//span)[1]");
    public static By suite_name = By.xpath("(//div[@class=\"text-left\"]//span)[3]");
    public static By textName = By.xpath("//*[@class=\"p-datatable-header\"]");
    public static By suiteIDList = By.xpath("//tr/td[1]//span/span");
    public static By testcase_COUNT = By.xpath("(//div[@class=\"text-left\"]/span)[4]");
    public static By zeroTestCase = By.xpath("//div[text()=\"0 Testcase(s) Found. Create/Add new Testcase(s) to execute Suite.\"]");
    public static By getTheStatus = By.xpath("(//div[@class=\"text-center\"]/div)[1]");
    public static By elementDivtext = By.xpath("//div[@class=\"dialogExecuteSuite\"]");
    public static By linkClick = By.xpath("//div[@class=\"container text-center  mt-3\"]/a");
    public static By hasNext2 = By.xpath("//button[text()=\"1\"]");
    public static By hasNext3 = By.xpath("//button[text()=\"3\"]");
    public static By hasNext4 = By.xpath("//button[text()=\"4\"]");
    public static By buttons = By.xpath("//span[@class=\"p-paginator-pages\"]/button");
    public static By nextPageBtn = By.xpath("//button[@aria-label='Next Page']");
    public static By playicon = By.xpath("(//*[local-name()='svg' and @data-icon='circle-play']/*[local-name()='path'])[1]");
    public static By playicon2 = By.xpath("(//*[local-name()='svg' and @data-icon='circle-play']/*[local-name()='path'])[3]");
    public static By playiconCross = By.xpath("//span[@class=\"p-dialog-header-close-icon pi pi-times\"]");
    public static By addDataButton = By.xpath("//button[text()=\"Add Data\"]");
    public static By modeScroll = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[1]");
    public static By modeSelect = By.xpath("//li[text()=\"Sequence\"]");
    public static By envScroll = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[2]");
    public static By envSelect = By.xpath("//li[text()=\"Beta\"]");
    public static By url = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[3]");
    public static By addDataOpt = By.xpath("(//div[@class=\"p-dropdown-trigger\"])[4]");
    public static By addDataInput = By.xpath("(//input[@placeholder=\"Value\"])[2]");
    public static By urlSelect = By.xpath("//li[text()=\"base_url\"]");
    public static By valueInput = By.xpath("(//input[@placeholder=\"Value\"])[1]");
    public static By addDataCross = By.xpath("(//div[@class=\"text-center col-md-1 col-sm-1\"])[2]");
    public static By executeButton = By.xpath("//button[text()=\"Execute\"]");
    public static By select_gempyp = By.xpath("(//span[text()=\"Select\"])[1]");
    public static By back_gem_opt = By.xpath("(//span[text()=\"Back\"])[1]");
    public static By select_pr_name = By.xpath("//div[@class=\"p-dropdown-trigger\"]");
    public static By GEMeCO_api = By.xpath("(//li[text()=\"GEMECO-API-PY\"])[1]");
    public static By input_suite_nm = By.xpath("//input[@placeholder=\"Suite Name\"]");
    public static By create_suite = By.xpath("//button[text()=\"Create Suite\"]");
    public static By allFields = By.xpath("//div[text()=\"suite with this name exists for this project\"]");

    public static By suite_created = By.xpath("//div[text()=\"Suite Created Successfully !\"]");
    public static By new_uniq = By.xpath("(//div[@class=\"text-left\"]/span)[2]");
    public static By total_COunt = By.xpath("//span[@class=\"p-paginator-current\"]");
    public static By suite_id_btn = By.xpath("//span[text()=\"Suite ID\"]");
    public static By select_Zero = By.xpath("(//div[@class=\"p-checkbox p-component\"])[2]");
    public static By zeroText = By.xpath("//span[@class=\"image-text\"]/span[text()=\"0\"]");
    public static By zero_list = By.xpath("//tr/td[5]//span/span");
    public static By filterBroken = By.xpath("(//span[@class=\"pi pi-filter-icon pi-filter\"])[5]");
    public static By testcaseID = By.xpath("(//span[@class=\"pi pi-filter-icon pi-filter\"])[10]");
    public static By noTestCase = By.xpath("//strong[contains(text(),'No TestCase(s) Found')]");
    public static By createTestcase = By.xpath("//td/center");
    public static By testCaseIdText = By.xpath("//span[@class=\"image-text\"]/span[text()=\"28\"]");
    public static By testCaseIdTexts = By.xpath("//td[@class=\"columnsPrime  maxWidthTableText \"][1]");
}

